### PR TITLE
chore(deps): upgrade styled-components to v5

### PR DESCRIPTION
**Pull request by austingreendev**
## Description

This PR upgrades `styled-components` to v5 and upgrades our related tooling and tests.

## Detail

@jzempel there are some unique warnings about our `StyledThumb` implementation in `Range` that I'm not able to decipher. Can you take a look in the CircleCI jest logs?

## Checklist

- [ ] :ok_hand: design updates are Garden Designer approved (add the
      designer as a reviewer)
- [x] :globe_with_meridians: demo is up-to-date (`yarn start`)
- [x] :arrow_left: renders as expected with reversed (RTL) direction
- [x] :metal: renders as expected with Bedrock CSS (`?bedrock`)
- [x] :wheelchair: analyzed via [axe](https://www.deque.com/axe/) and evaluated using VoiceOver
- [x] :guardsman: includes new unit tests
- [x] :memo: tested in Chrome, Firefox, Safari, Edge, and IE11

### CODE REVIEW

**Comment by jzempel** [comment]
The jest warning appear to be connected to https://github.com/zendeskgarden/react-components/blob/8fb1326568572622a18ca47c0777bd4c2be07008/packages/colorpickers/src/styled/Colorpicker/StyledAlphaRange.ts#L34-L35. However, this construct is absolutely intentional and necessary to get the `Range` inheritance styled as expected. Refactoring would be beyond the scope of this PR. Is there a way to get the console warnings dialed back?

**Review by jzempel — APPROVED** [review]

**Review by jzempel — CHANGES_REQUESTED** [review]
The background on the `Colorpicker` alpha slider is whacked.

**Comment by jzempel** [comment]
Ugh, from what I'm seeing, it looks as if `styled-components` is no longer honoring the `backgroundSize` followed by `background`. When I remove the line 34 shown above, I'm able to locally reproduce what we see in the production staging deploy.

It could be that `Range` will need to receive an internal (i.e. `/** @ignore */`) prop that allows us to knock-out background sizing while it is being extended by these `Colorpicker` components. TBH, it would also allow the accompanying logic to be knocked-out.

https://github.com/zendeskgarden/react-components/blob/8fb1326568572622a18ca47c0777bd4c2be07008/packages/forms/src/elements/Range.tsx#L22-L55

**Comment by austingreendev** [comment]
@jzempel for the colorpicker checkered background logic to work I think we need to split the `checkeredBackground` utility into the equivalent shorthand CSS properties. I've been trying this, but I'm not able to match the original styling you intended. Could you give `StyledAlphaRange` implementation a look?

**Comment by jzempel** [comment]
@austingreendev I think this is going to be a lot more straightforward to apply a prop to the underlying `Range` that knocks out the `backgroundSize` styling. Splitting up the `checkeredBackground` logic isn't going to result in code we want to maintain going forward.

**Review by jzempel — APPROVED** [review]

**Pull request merged**
