### PR TITLE
chore(deps): remove .template from renovate updates

### PR DESCRIPTION
**Pull request by Francois-Esquire**
## Description

Removes `packages/.template/` directory from being updated on shared package updates since it causes artifact corruption with Renovate.

## Checklist

- [ ] :ok_hand: ~design updates will be Garden Designer approved (add the designer as a reviewer)~
- [ ] :globe_with_meridians: ~demo is up-to-date (`yarn start`)~
- [ ] :arrow_left: ~renders as expected with reversed (RTL) direction~
- [ ] :metal: ~renders as expected with Bedrock CSS (`?bedrock`)~
- [ ] :guardsman: ~includes new unit tests. Maintain [existing coverage](https://coveralls.io/github/zendeskgarden/react-components?branch=main) (always >= 96%)~
- [ ] :wheelchair: ~tested for [WCAG 2.1 AA](https://www.w3.org/WAI/WCAG21/quickref/?currentsidebar=%23col_customize&levels=aaa) accessibility compliance~
- [ ] :memo: ~tested in Chrome, Firefox, Safari, and Edge~

### CODE REVIEW

**Review by jzempel — COMMENTED** [review]
Is there an example commit where corruption happened?

**Comment by Francois-Esquire** [comment]
> Is there an example commit where corruption happened?

Yes! There is currently an open PR #1527 that contains [issues with the artifact](https://github.com/zendeskgarden/react-components/pull/1527#issuecomment-1493494821) due to the template syntax found in the source files (specifically `package.json`).

**Comment by jzempel** [comment]
> contains issues with the artifact due to the template syntax

...isn't exactly corruption. In fact, expected. Do you think it's fair to expect maintainers to understand why `.template` contains malformed files in favor of keeping the template `yarn.lock` updated? As I see it, what's happening on the referenced PR is desirable and can be manually merged once the build is fixed and the deployment tested.

**Comment by Francois-Esquire** [comment]
> > contains issues with the artifact due to the template syntax
> 
> ...isn't exactly corruption. In fact, expected. Do you think it's fair to expect maintainers to understand why `.template` contains malformed files in favor of keeping the template `yarn.lock` updated? As I see it, what's happening on the referenced PR is desirable and can be manually merged once the build is fixed and the deployment tested.

That makes sense to me, closing!

**Pull request closed without merging**
