### PR TITLE
fix(deps): upgrade polished dep due to security vulnerability

### PR DESCRIPTION
**Pull request by JamesSingleton**
https://app.snyk.io/vuln/npm:polished

                                                                                                                      

## Description

Upgrades the `polished` dependency to address https://app.snyk.io/vuln/npm:polished

## Checklist

- [ ] :ok_hand: design updates are Garden Designer approved (add the
      designer as a reviewer)
- [ ] :globe_with_meridians: demo is up-to-date (`yarn start`)
- [ ] :arrow_left: renders as expected with reversed (RTL) direction
- [ ] :metal: renders as expected with Bedrock CSS (`?bedrock`)
- [ ] :wheelchair: analyzed via [axe](https://www.deque.com/axe/) and evaluated using VoiceOver
- [ ] :guardsman: includes new unit tests
- [ ] :memo: tested in Chrome, Firefox, Safari, Edge, and IE11

### CODE REVIEW

**Comment by hzhu** [comment]
Looks good. What was the steps (commands) to make this upgrade? I want to verify it locally on my machine.

**Comment by JamesSingleton** [comment]
> Looks good. What was the steps (commands) to make this upgrade? I want to verify it locally on my machine.

@hzhu, unfortunately, `yarn` does not give an easy way to upgrade sub dependencies like `npm`. Basically what I had to do was `rm yarn.lock && yarn install`. Copy the bit for `polished` from the `yarn.lock` file and then `git checkout .` and replace the old `polished` in the `yarn.lock` with the new. Doing anything like `yarn upgrade` or `yarn upgrade polished@latest` didn't work as doing `yarn upgrade polished@latest` is like doing `yarn add polished@latest`. There is a GitHub [Issue](https://github.com/yarnpkg/yarn/issues/2394) in yarn that talks about this and it not getting native support in yarn.

**Comment by JamesSingleton** [comment]
@hzhu actually might have to decline this PR as it looks like I might have to update `@babel/runtime` as well... But let me know.

**Comment by hzhu** [comment]
It looks like polished isn't a shared dependency at the root mono repo level, and the dependency found in the root `yarn.lock` is a result of an indirect dependency. Notice that polished isn't found in the root `package.json`. Also, this project strives to not directly modify the `yarn.lock` manually.

There are sub-packages that use polished, and those may be the packages that you're looking to upgrade? E.g. `react-forms`, `react-colorpickers`.

**Comment by JamesSingleton** [comment]
@hzhu the issue looks to be `@zendeskgarden/react-theming` as it requires `polished@^4.0.0`. However, when installed into new deps it will install whatever is the latest at the time.

**Comment by hzhu** [comment]
@JamesSingleton 

Looks like `react-theming` is one of the sub-packages that use polished. You could try `yarn upgrade polished` which should update the corresponding sub-package `yarn.lock` file. 

Since polished isn't a cross-package dependency (e.g not defined at the top-level `package.json`), I think the top level `yarn.lock` should remain unchanged. It should update accordingly as cross-package dependencies update to later versions of polished. These top-level dependencies are managed by Renovate.

**Comment by hzhu** [comment]
@JamesSingleton any updates on this one?

**Pull request closed without merging**
