### PR TITLE
fix(dropdowns.next): active listbox option and menu item styling

### PR DESCRIPTION
**Pull request by jzempel**
## Description

Use box-shadow styling to add a **full** activation border to:
- `Combobox` listbox `Option`
- `Menu` `Item`

### CODE REVIEW

**Comment by jzempel** [comment]
@lucijanblagonic here's the corresponding storybook deployment: https://6552a5d810118432ce22c5b5--jzempel.netlify.app/?path=/story/packages-dropdowns-next-combobox--uncontrolled

**Comment by lucijanblagonic** [comment]
> @lucijanblagonic here's the corresponding storybook deployment: https://6552a5d810118432ce22c5b5--jzempel.netlify.app/?path=/story/packages-dropdowns-next-combobox--uncontrolled

Since this is an `inset` focus style, the border should be `2px` thick. I was basing the reasoning from the previous focus state styling research we did, including the [WCAG 2.2](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance.html). Is there a reason you pick `1px`?

**Comment by jzempel** [comment]
> Is there a reason you pick `1px`?

I was dereferencing the wrong theming value. Here's the updated deployment with `2px` activation box-shadow: https://6553aa0855ce51008cb3c865--jzempel.netlify.app/?path=/story/packages-dropdowns-next-combobox--uncontrolled

**Comment by jzempel** [comment]
design style rejected

**Pull request closed without merging**
